#------Taking input form user------
Name=input("Enter your Name: ")
print("Hello" + Name)
age= (input("Enter your age"))
print("Hello" + Name + "your age: " +age)
Name1=input("Enter first Nmae: ")
Name2=input("Enter second Name: ")
print(Name1+Name2)
x,y=input("enter a two value:").split()
print("no of boys: ",x)
print("no of girls: ",y)
x,y,z=input("enter a three value:").split()
print("Total of student: ", x )
print("Total of boys: ", y)
print("Total of girls:",z)
friends=["sneha","rohini","shivani"]
print(friends[1])
print(friends[2])